tuple_list = ('Iraq', 'Jordon', 'Malaysia', 'Turkey', 'Japan')
print(tuple_list)
choose = str(input('Enter the name of country  : ')).capitalize()
print(tuple_list.index(choose))
choose = int(input('Enter number to show country  : '))
print(tuple_list[choose])
