file_open = open('Names.txt', 'r')
print(file_open.read())
file_open.close()
ask = str(input('Enter a name to add to file : '))
file_write = open('Names.txt', 'a')
file_write.write(file_write + '\n')
file_write.close()
file_open = open('Names.txt', 'r')
print(file_open.read())
